# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 671b7b4d911e6c388c5503a3901438fb54d844124855bc4814d529adf7962f6ee06c1d870fed0dcc7661c1ebb1516fded4acc7b4625827518e40800a7aee6012

test:
  secret_key_base: 4da1e535445e043259aaedc644eb0850deca156b69358e654affb50830620d073f6709450e8404f93743ccfd2add1096130c37dceadb9752fb0d4e92f40a9313

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
